### ISSUE TITLE
Ability determine the content type if the MIME-type or extension is not provided

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata#110]
Based on the file / stream content, be able to detect the following formats:
* [x] APE (Monkey's Audio): sindresorhus/file-type#151
* [x] FLAC
* [x] MP3
* [x] Ogg
* [x] WMA, blocked by sindresorhus/file-type#123
* [x] WAV, works with wrong MIME-type: sindresorhus/file-type#149
* [x] MPEG-4 Audio, works with wrong MIME-type: sindresorhus/file-type#147
* [x] WavPack: sindresorhus/file-type#157

Required for captbaritone/webamp#606

**Comment by Borewit** [comment]
MPEG-4 audio results in invalid MIME-type: sindresorhus/file-type#147

**Comment by Borewit** [comment]
At least: FLAC, MP3, Ogg, WAV & MPEG4 implemented in [v2.3.0](https://github.com/Borewit/music-metadata/releases/tag/v2.3.0).

**Comment by Borewit** [comment]
Implemented in [v2.4.3](https://github.com/Borewit/music-metadata/releases/tag/v2.4.3).

**Comment by gravelld** [comment]
I'm a little puzzled by what I should be expecting for the mime type.

MP3s seem to give `audio/mpeg` - shouldn't this be `audio/mp3`? MPEG is a bit ambiguous...

Also, OGGs give `video/ogg` for OGGs without a video stream.

**Comment by Borewit** [comment]
No, the MIME type for MP3 is [`audio/mpeg`](https://www.iana.org/assignments/media-types/audio/mpeg).

> MP3s seem to give audio/mpeg - shouldn't this be audio/mp3? MPEG is a bit ambiguous...

I think the whole MP3 format is pretty ugly. But in general I think the specification of the container format is sufficient. But my opinion doesn't matter, [`audio/mpeg`](https://www.iana.org/assignments/media-types/audio/mpeg) is what is been standardized. Using `audio/mp3` is non compliant.

Type detection is done by [file-type](https://github.com/sindresorhus/file-type). I am one of the maintainers on that one.

It may require very deep analysis of the file to determine if it just an audio or has a video stream embedded as well. For [music-metadata](https://github.com/Borewit/music-metadata) the container format is sufficient (so audio/ogg & video/ogg will end up in the same parser). In other context this may be important to be able to distinct these.

**Comment by gravelld** [comment]
Thanks for correcting me on that :+1:
